bucket:
  strip: 1
packages:
  - name: foodtrack-node 
    actions:
      - &default_action
        environment:
          username: ${username}
          password: ${password}
          database: ${database}
  
        limits:
          timeout: 10000
          
        name: test
        runtime: nodejs:default
        
      - <<: *default_action
        name: admin
        
      - <<: *default_action
        name: beneficiary
        
      - <<: *default_action
        name: login       
                
      - <<: *default_action
        name: shop