bucket:
  strip: 1
packages:
  - name: foodtrack-node 
    actions:
      - &default_action
        environment:
          USERNAME: ${USERNAME}
          PASSWORD: ${PASSWORD}
          DATABASE: ${DATABASE}
  
        limits:
          timeout: 6000
          
        name: test
        runtime: nodejs:default
        
      - <<: *default_action
        name: admin
        
      - <<: *default_action
        name: beneficiary
        
      - <<: *default_action
        name: login       
                
      - <<: *default_action
        name: shop