# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g https://apigcp.nimbella.io/downloads/nim/nimbella-cli.tgz
      - run: npm ci
      - run: npm run ci:deploy

    env:
      username: ${{ secrets.username }}
      password: ${{ secrets.password }}
      database: ${{ secrets.database }}
